import { renderPageLayout } from "./layout.js";
export function renderAgentsPageHtml(): string {
const extraStyles=`.agents{max-width:1180px;margin:0 auto;padding:clamp(3rem,8vw,7rem) 2rem}.agents-hero{display:grid;grid-template-columns:1fr .9fr;gap:5rem;align-items:end}.agents-hero span{color:var(--blue);font-weight:800;font-size:.74rem;letter-spacing:.1em}.agents h1{font-size:clamp(2.6rem,5vw,5rem);line-height:.98;letter-spacing:-.065em;margin:.65rem 0 0}.agents-hero p{color:var(--text-muted);line-height:1.65;font-size:1rem}.agent-flow{margin-top:5rem;display:grid;grid-template-columns:1.1fr .9fr;gap:2rem;align-items:stretch}.flow-list{border-top:1px solid var(--border)}.flow-list article{padding:1.35rem 0;border-bottom:1px solid var(--border);display:grid;grid-template-columns:48px 1fr;gap:1rem}.flow-list b{font-family:var(--mono);color:var(--blue);font-size:.77rem}.flow-list h2{font-size:1rem;letter-spacing:-.025em}.flow-list p{font-size:.87rem;color:var(--text-muted);line-height:1.55;margin-top:.25rem}.agent-code{background:#172131;border-radius:18px;padding:clamp(1.4rem,3vw,2.5rem);color:#deebf8;box-shadow:0 20px 40px rgba(20,38,60,.17);font-family:var(--mono);font-size:.78rem;line-height:1.8;overflow:auto}.dim{color:#8ca3b9}.key{color:#8fd3ff}.value{color:#9de4bf}.agent-note{margin-top:4rem;padding-top:1.4rem;border-top:1px solid var(--border);display:flex;justify-content:space-between;gap:2rem}.agent-note h2{font-size:1.4rem;letter-spacing:-.04em}.agent-note p{max-width:490px;color:var(--text-muted);font-size:.9rem;line-height:1.6}@media(max-width:760px){.agents{padding:3rem 1.2rem}.agents-hero,.agent-flow{grid-template-columns:1fr;gap:2rem}.agent-flow{margin-top:3rem}.agent-note{display:block;margin-top:3rem}.agent-note p{margin-top:.6rem}}`;
const bodyContent=`<main class="agents"><header class="agents-hero"><div><span>FOR AI AGENTS</span><h1>Public service actions need a real interface.</h1></div><p>Raksha exposes a typed, discoverable protocol so an agent can assist a citizen without scraping a portal or claiming an action it cannot verify.</p></header><section class="agent-flow"><div class="flow-list"><article><b>01</b><div><h2>Discover capabilities</h2><p>Agents inspect actions and confirmation requirements before beginning.</p></div></article><article><b>02</b><div><h2>Build a case carefully</h2><p>Natural language and evidence travel through the same reconciliation flow as every human channel.</p></div></article><article><b>03</b><div><h2>Require citizen confirmation</h2><p>High-risk submission is guarded. The agent cannot silently send a report.</p></div></article><article><b>04</b><div><h2>Return an auditable result</h2><p>CAP returns a typed case response and event trail rather than a fabricated success message.</p></div></article></div><pre class="agent-code"><span class="dim">// POST /mcp</span>
{
  <span class="key">"method"</span>: <span class="value">"tools/call"</span>,
  <span class="key">"params"</span>: {
    <span class="key">"name"</span>: <span class="value">"raksha_submit_incident"</span>,
    <span class="key">"arguments"</span>: { <span class="key">"confirmedByCitizen"</span>: <span class="value">true</span> }
  }
}</pre></section><footer class="agent-note"><h2>One safety rule is non-negotiable.</h2><p>Agents can collect, clarify, and prepare. They may only submit when the citizen has explicitly confirmed the verified report.</p></footer></main>`;
return renderPageLayout({title:"Raksha for AI agents",activeNav:"agents",bodyContent,extraStyles});}
